name: cloudformation nag (cfn-nag)

on: [pull_request, push]

#or
# on:
#   pull_request_target:
#     branches:
#       - main

jobs:
  validar_cfn_nag:
    name: Validate cfn_nag (vulnerabilities)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Install cfn_nag via gem
      #   run: |
      #     eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      #     brew install ruby brew-gem
      #     brew gem install cfn-nag

      # - name: Check for vulnerabilities
      #   run: |
      #     pwd
      #     ls -lsa
      #     eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      #     cfn_nag_scan --input-path "${GITHUB_WORKSPACE}/main.yaml" 

      - name: Simple test
        uses: stelligent/cfn_nag@master
        with:
          input_path: main.yaml

  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint -t ./main.yaml

  Validate:
    name: Validate
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Validate cloudformation template
      run: |
        aws cloudformation validate-template --template-body file://main.yaml 