name: Cloudformation nag
on: [push]
# on:
#   pull_request_target:
#     branches:
#       - main

jobs: 
    cloudformation-nag:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            
            - run: |
                eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
                brew install ruby brew-gem
                brew gem install cfn-nag
                
