name: Cloudformation nag
on: [push]
# on:
#   pull_request_target:
#     branches:
#       - main

jobs: 
    cloudfomation-nag:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
            - run: brew install ruby brew-gem
            - run: brew gem install cfn-nag 
