name: Validate templates
on: [push]

# Github actions es gratis, entonces podemos aprovechar correr nuestras pruebas en cada
# push a una rama nueva. Si necesitamos ahorrar en tiempo de ejecucion, podriamos solo
# correr nuestros worlflows cuando craemos un pull request. Asi:
# on:
#   pull_request_target:
#     branches:
#       - main
#   push:
#     branches:
#       - main

jobs:
  cfn-nag:
    name: Validate security practices (cfn-nag)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Simple test
        uses: stelligent/cfn_nag@master
        with:
          input_path: ./main.yaml

      # Manual steps
      # - name: Setup cfn-nag
      #   run: |
      #     eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      #     brew install ruby brew-gem
      #     brew gem install cfn-nag

      # - name: Execute cfn-nag
      #   run: |
      #     eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      #     cfn_nag_scan --input-path ./main.yaml

  cfn-lint:
    name: Perform linting (cfn-lint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint -t ./main.yaml

  cnf-validate:
    name: Validate cfn template (aws-cli)
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Validate cloudformation template
      run: |
        aws cloudformation validate-template --template-body file://main.yaml
