name: cloudformation nag (cfn-nag)

on: [pull_request, push]

#or
# on:
#   pull_request_target:
#     branches:
#       - main

jobs:
  validar_cfn_nag:
    name: Validate cfn_nag (vulnerabilities)
    runs-on: ubuntu-latest

    steps:
      - name: Install cfn_nag via gem
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install ruby brew-gem
          brew gem install cfn-nag

      - name: Check for vulnerabilities
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          cfn_nag_scan --input-path ${{ github.workspace }}/main.yaml 


