name: Lint CloudFormation Templates

on: [push]

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Cloud Formation Linter with Latest Version
        run: |
          gh repo clone aws-cloudformation/cfn-lint
          cd cfn-lint
          python setup.py clean --all
          python setup.py install
          pip install cfn-lint

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint -t ./main.yaml --non-zero-exit-code error